DROP TABLE beneficios CASCADE;
DROP TABLE tener_participaciones CASCADE;
DROP TABLE usuario_mercado CASCADE;
DROP TABLE usuario_empresa CASCADE;
DROP TABLE usuario_inversor;
DROP TABLE usuario_regulador;
DROP TABLE anuncio_venta;
DROP TABLE parte_compra;
DROP TABLE compra;
DROP TYPE enum_estado;