/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gal.usc.mercadovalores.gui;
import gal.usc.mercadovalores.aplicacion.UsuarioDeMercado;
import gal.usc.mercadovalores.aplicacion.UsuarioInversor;
import gal.usc.mercadovalores.aplicacion.UsuarioEmpresa;

import gal.usc.mercadovalores.aplicacion.AnuncioVenta;
import gal.usc.mercadovalores.db.FachadaDB;
import java.util.Set;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class VAnunciosUsuario extends javax.swing.JFrame {
    private UsuarioDeMercado usr;
    /**
     * Creates new form VAnunciosUsuario
     */
    public VAnunciosUsuario(UsuarioDeMercado usr) {
        initComponents();
        this.usr = usr;
        this.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAnuncios = new javax.swing.JTable();
        botonDarDeBaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaAnuncios.setModel(new TablaAnunciosUsuario());
        jScrollPane1.setViewportView(tablaAnuncios);

        botonDarDeBaja.setText("Dar de baja");
        botonDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarDeBajaActionPerformed(evt);
            }
        });

        jLabel1.setText("Anuncios de");

        labelUsuario.setText("usuario");

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonDarDeBaja))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsuario)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDarDeBaja)
                    .addComponent(botonSalir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        //salimos de la ventana
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDarDeBajaActionPerformed
        //damos de baja el anuncio
        try{
            TablaAnunciosUsuario tA = (TablaAnunciosUsuario) this.tablaAnuncios.getModel();
            AnuncioVenta aV = tA.obtenerParticipacion(this.tablaAnuncios.getSelectedRow());
            FachadaDB.getFachada().bajaAnuncioVenta(aV);
        }catch(Exception e){
            VAviso x = new VAviso(this,true,e.getMessage());
            x.setVisible(true);
        }
        this.updateTable();
    }//GEN-LAST:event_botonDarDeBajaActionPerformed

    private void updateTable(){
        
        if(this.usr instanceof UsuarioInversor){
            UsuarioInversor tmp = (UsuarioInversor)this.usr;
            this.labelUsuario.setText(tmp.getNombreCompleto());
        }else{
            UsuarioEmpresa tmp = (UsuarioEmpresa)this.usr;
            this.labelUsuario.setText(tmp.getNombreComercial());
        }
        
        TablaAnunciosUsuario tA = (TablaAnunciosUsuario) this.tablaAnuncios.getModel();
        Set<AnuncioVenta> setAnuncios = FachadaDB.getFachada().getAnunciosUsuario(this.usr);
        ArrayList<AnuncioVenta> arrAnuncios = new ArrayList<>();
        for(AnuncioVenta aV : setAnuncios){
            arrAnuncios.add(aV);
        }
        
        tA.setFilas(arrAnuncios);
        if(tA.getRowCount()>0){
            this.tablaAnuncios.setRowSelectionInterval(0, 0);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDarDeBaja;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTable tablaAnuncios;
    // End of variables declaration//GEN-END:variables
}
