/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gal.usc.mercadovalores.gui;
import gal.usc.mercadovalores.aplicacion.Usuario;
import gal.usc.mercadovalores.aplicacion.UsuarioEmpresa;
import gal.usc.mercadovalores.aplicacion.UsuarioRegulador;
import gal.usc.mercadovalores.aplicacion.UsuarioInversor;
import gal.usc.mercadovalores.aplicacion.FachadaAplicacion;
import gal.usc.mercadovalores.aplicacion.Participacion;
import gal.usc.mercadovalores.db.FachadaDB;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author icaro
 */
public class VPrincipalInversor extends javax.swing.JFrame {
    private UsuarioInversor usr;
    private FachadaAplicacion fa;
    private boolean modificando = false;
    /**
     * Creates new form VPrincipalMercado
     * 
     * @param usr
     */
    public VPrincipalInversor(UsuarioInversor usr, FachadaAplicacion fa) {
        this.usr = usr;
        this.fa = fa;
        initComponents();
        this.ActualizarTablaDatos();
        this.botonUpdate.setEnabled(this.modificando);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        SalirBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CerrarSesionBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonUpdate = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        CuentaMenu = new javax.swing.JMenu();
        ModificarMenuItem = new javax.swing.JMenuItem();
        BajaMenuItem = new javax.swing.JMenuItem();
        ParticipacionesMenu = new javax.swing.JMenu();
        VenderMenuItem = new javax.swing.JMenuItem();
        ComprarMenuItem = new javax.swing.JMenuItem();
        BajaVentaMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Inversor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ID", null},
                {"Saldo", null},
                {"Direccion", null},
                {"Telefono", null},
                {"DNI", null},
                {"Nombre Comercial", null},
                {"Clave", null},
                {"Participaciones", null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDatos.setCellSelectionEnabled(true);
        TablaDatos.setTableHeader(null);
        jScrollPane2.setViewportView(TablaDatos);

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Información del inversor:");

        CerrarSesionBoton.setText("Cerrar Sesión");
        CerrarSesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionBotonActionPerformed(evt);
            }
        });

        botonUpdate.setText("Actualizar");
        botonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 262, Short.MAX_VALUE)
                .addComponent(botonUpdate))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(botonUpdate))
        );

        CuentaMenu.setText("Cuenta");

        ModificarMenuItem.setText("Modificar Datos");
        ModificarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMenuItemActionPerformed(evt);
            }
        });
        CuentaMenu.add(ModificarMenuItem);

        BajaMenuItem.setText("Solicitar Baja");
        BajaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaMenuItemActionPerformed(evt);
            }
        });
        CuentaMenu.add(BajaMenuItem);

        Menu.add(CuentaMenu);

        ParticipacionesMenu.setText("Participaciones");

        VenderMenuItem.setText("Vender");
        VenderMenuItem.setToolTipText("");
        VenderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderMenuItemActionPerformed(evt);
            }
        });
        ParticipacionesMenu.add(VenderMenuItem);

        ComprarMenuItem.setText("Comprar");
        ComprarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarMenuItemActionPerformed(evt);
            }
        });
        ParticipacionesMenu.add(ComprarMenuItem);

        BajaVentaMenuItem.setText("Dar de baja venta");
        BajaVentaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaVentaMenuItemActionPerformed(evt);
            }
        });
        ParticipacionesMenu.add(BajaVentaMenuItem);

        Menu.add(ParticipacionesMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CerrarSesionBoton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirBoton)
                    .addComponent(CerrarSesionBoton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //salimos de la aplicación
    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    private void CerrarSesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionBotonActionPerformed
        fa.cerrarSesion(this);
    }//GEN-LAST:event_CerrarSesionBotonActionPerformed

    private void BajaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaMenuItemActionPerformed
        //solicitud de las bajas:
        FachadaDB.getFachada().solicitarBaja(this.usr);
    }//GEN-LAST:event_BajaMenuItemActionPerformed

    private void ModificarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMenuItemActionPerformed
        //modificacion de los datos:
        //ponemos como visible el boton:
        this.modificando = !this.modificando;
        this.botonUpdate.setEnabled(this.modificando);
    }//GEN-LAST:event_ModificarMenuItemActionPerformed

    private void botonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpdateActionPerformed
        
        String idCheck = (String) this.TablaDatos.getValueAt(0, 1);
        String passCheck = (String) this.TablaDatos.getValueAt(6, 1);
        if(!idCheck.isEmpty() && !passCheck.isEmpty()){
            //actualizamos el usuario local
            String idActual = this.usr.getId();
            this.usr.setId((String) this.TablaDatos.getValueAt(0, 1));
            //this.usr.setSaldo((double) this.TablaDatos.getValueAt(1, 1));
            this.usr.setDireccion((String) this.TablaDatos.getValueAt(2, 1));
            this.usr.setTelefono((String) this.TablaDatos.getValueAt(3, 1));
            this.usr.setDni((String) this.TablaDatos.getValueAt(4, 1));
            this.usr.setNombreCompleto((String) this.TablaDatos.getValueAt(5,1));
            this.usr.setClave((String) this.TablaDatos.getValueAt(6,1));


            Usuario res;
            res = FachadaDB.getFachada().getUsuarioById(this.usr.getId());

            if(res != null && res.getId().equals(idActual)){
                FachadaDB.getFachada().actualizarUser(this.usr);
            }else if(res != null ){
                VAviso x = new VAviso(this,true,"Nombre de usuario ya en uso, por favor elige otro.");
                x.setVisible(true);
                this.usr.setId(idActual);
            }else{
                try{
                    FachadaDB.getFachada().add(this.usr);
                }catch(Exception e){
                    VAviso x = new VAviso(this,true,e.getMessage());
                    x.setVisible(true);
                }
            }
        }else{
            VAviso x = new VAviso(this,true,"Los campos no pueden estar vacíos.");
            x.setVisible(true);
        }
        
        this.ActualizarTablaDatos();

    }//GEN-LAST:event_botonUpdateActionPerformed

    private void ComprarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarMenuItemActionPerformed
    }//GEN-LAST:event_ComprarMenuItemActionPerformed

    private void VenderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderMenuItemActionPerformed
        this.fa.ventanaVender(this.usr);
    }//GEN-LAST:event_VenderMenuItemActionPerformed

    private void BajaVentaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaVentaMenuItemActionPerformed
        // TODO add your handling code here:
        this.fa.ventanaAnuncios(this.usr);
    }//GEN-LAST:event_BajaVentaMenuItemActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ActualizarTablaDatos();
    }//GEN-LAST:event_formWindowActivated

    private void ActualizarTablaDatos(){
        try{
            this.usr = (UsuarioInversor)FachadaDB.getFachada().getUsuarioById(this.usr.getId());
            int n_part = 0;

            for(Participacion part: FachadaDB.getFachada().getParticipacionesUsuarioDeMercado(usr)){
                n_part += part.getNumero();
            }
            this.TablaDatos.setValueAt(usr.getId(), 0, 1);
            this.TablaDatos.setValueAt(usr.getSaldo(), 1, 1);
            this.TablaDatos.setValueAt(usr.getDireccion(), 2, 1);
            this.TablaDatos.setValueAt(usr.getTelefono(), 3, 1);
            this.TablaDatos.setValueAt(usr.getDni(), 4, 1);
            this.TablaDatos.setValueAt(usr.getNombreCompleto(), 5, 1);
            this.TablaDatos.setValueAt(usr.getClave(), 6, 1);
            this.TablaDatos.setValueAt(n_part, 7, 1);
        }catch(Exception e){
            VAviso x = new VAviso(this,true,"Los campos no pueden estar vacíos.");
            x.setVisible(true);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BajaMenuItem;
    private javax.swing.JMenuItem BajaVentaMenuItem;
    private javax.swing.JButton CerrarSesionBoton;
    private javax.swing.JMenuItem ComprarMenuItem;
    private javax.swing.JMenu CuentaMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem ModificarMenuItem;
    private javax.swing.JMenu ParticipacionesMenu;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JMenuItem VenderMenuItem;
    private javax.swing.JButton botonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
