/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gal.usc.mercadovalores.gui;

/**
 *
 * @author icaro
 */
public class VPrincipalInversor extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipalMercado
     */
    public VPrincipalInversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        SalirBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        CuentaMenu = new javax.swing.JMenu();
        ModificarMenuItem = new javax.swing.JMenuItem();
        BajaMenuItem = new javax.swing.JMenuItem();
        ParticipacionesMenu = new javax.swing.JMenu();
        VenderMenuItem = new javax.swing.JMenuItem();
        ComprarMenuItem = new javax.swing.JMenuItem();
        BajaVentaMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana  Mercado");

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ID", null},
                {"Saldo", null},
                {"Direccion", null},
                {"Telefono", null},
                {"DNI", null},
                {"Nombre Comercial", null},
                {"Participaciones ", null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        TablaDatos.setCellSelectionEnabled(true);
        TablaDatos.setTableHeader(null);
        jScrollPane2.setViewportView(TablaDatos);

        SalirBoton.setText("Salir");

        jLabel1.setText("Información del usuario:");

        CuentaMenu.setText("Cuenta");

        ModificarMenuItem.setText("Modificar Datos");
        CuentaMenu.add(ModificarMenuItem);

        BajaMenuItem.setText("Solicitar Baja");
        CuentaMenu.add(BajaMenuItem);

        Menu.add(CuentaMenu);

        ParticipacionesMenu.setText("Participaciones");

        VenderMenuItem.setText("Vender");
        VenderMenuItem.setToolTipText("");
        ParticipacionesMenu.add(VenderMenuItem);

        ComprarMenuItem.setText("Comprar");
        ParticipacionesMenu.add(ComprarMenuItem);

        BajaVentaMenuItem.setText("Dar de baja venta");
        ParticipacionesMenu.add(BajaVentaMenuItem);

        Menu.add(ParticipacionesMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 258, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(SalirBoton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BajaMenuItem;
    private javax.swing.JMenuItem BajaVentaMenuItem;
    private javax.swing.JMenuItem ComprarMenuItem;
    private javax.swing.JMenu CuentaMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem ModificarMenuItem;
    private javax.swing.JMenu ParticipacionesMenu;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JMenuItem VenderMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
