/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gal.usc.mercadovalores.gui;
import gal.usc.mercadovalores.aplicacion.EstadoUsuario;
import gal.usc.mercadovalores.aplicacion.UsuarioRegulador;
import gal.usc.mercadovalores.aplicacion.FachadaAplicacion;
import gal.usc.mercadovalores.aplicacion.UsuarioDeMercado;
import gal.usc.mercadovalores.db.FachadaDB;
import java.util.Set;
import java.util.ArrayList;



/**
 *
 * @author user
 */
public class VPrincipalAdmin extends javax.swing.JFrame {
    private UsuarioRegulador usr;
    private FachadaAplicacion fa;
    /**
     * Creates new form VPrincipalAdmin
     * @param usr
     */
    public VPrincipalAdmin(UsuarioRegulador usr, FachadaAplicacion fa) {
        this.usr = usr;
        this.fa = fa;
        initComponents();
        this.updateTabla();
        this.displayComision();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalirBoton = new javax.swing.JButton();
        ComisionActualCajaTexto = new javax.swing.JTextField();
        NuevaComisionBoton = new javax.swing.JButton();
        ComisionActualTexto = new javax.swing.JLabel();
        BajaPagosBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        botonAutorizar = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        UsuarioMenu = new javax.swing.JMenu();
        SaldosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regulador");
        setBackground(new java.awt.Color(43, 45, 66));
        setResizable(false);

        SalirBoton.setText("Salir");
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        NuevaComisionBoton.setText("Actualizar");
        NuevaComisionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaComisionBotonActionPerformed(evt);
            }
        });

        ComisionActualTexto.setText("Comisión actual:");

        BajaPagosBoton.setText("Dar de baja pagos de beneficios");
        BajaPagosBoton.setToolTipText("");
        BajaPagosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaPagosBotonActionPerformed(evt);
            }
        });

        tablaUsuarios.setModel(new TablaUsuarios());
        jScrollPane1.setViewportView(tablaUsuarios);

        botonAutorizar.setText("Autorizar");
        botonAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAutorizarActionPerformed(evt);
            }
        });

        botonCerrarSesion.setText("Cerrar Sesion");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        UsuarioMenu.setText("Usuarios");

        SaldosMenuItem.setText("Modifcar saldos");
        SaldosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldosMenuItemActionPerformed(evt);
            }
        });
        UsuarioMenu.add(SaldosMenuItem);

        Menu.add(UsuarioMenu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NuevaComisionBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComisionActualTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ComisionActualCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BajaPagosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonAutorizar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCerrarSesion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComisionActualTexto)
                    .addComponent(ComisionActualCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NuevaComisionBoton)
                .addGap(27, 27, 27)
                .addComponent(BajaPagosBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAutorizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirBoton)
                    .addComponent(botonCerrarSesion))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    //este boton permite autorizar las altas de usuarios nuevos
    private void botonAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAutorizarActionPerformed
        //si autorizo ->        
        TablaUsuarios uT = (TablaUsuarios) this.tablaUsuarios.getModel();
        UsuarioDeMercado user = uT.obtenerUsuario(this.tablaUsuarios.getSelectedRow());
        
        if(user.getEstado() == EstadoUsuario.SOLICITANDO_ALTA){
            FachadaDB.getFachada().autorizarRegistro(user);
        }else if(user.getEstado() == EstadoUsuario.SOLICITANDO_BAJA){
            FachadaDB.getFachada().autorizarBaja(user);
        }
        
        this.updateTabla();
        
    }//GEN-LAST:event_botonAutorizarActionPerformed

    private void SaldosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldosMenuItemActionPerformed
        //abrir ventana de los saldos
        this.fa.ventanaSaldos();
    }//GEN-LAST:event_SaldosMenuItemActionPerformed

    private void NuevaComisionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaComisionBotonActionPerformed
        //Actualizamos la comision actual
        if(!this.ComisionActualCajaTexto.getText().isEmpty()){
            this.usr.setComision_actual(Double.parseDouble(this.ComisionActualCajaTexto.getText()));
            FachadaDB.getFachada().actualizarComision(this.usr);
        }
    }//GEN-LAST:event_NuevaComisionBotonActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
        fa.cerrarSesion(this);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void BajaPagosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaPagosBotonActionPerformed
        this.fa.verBeneficios();
    }//GEN-LAST:event_BajaPagosBotonActionPerformed

    
    //funcion que actualiza usuarios de la tabla que se muestra al regulador
    //esto permite autorizar facilmente el alta y baja de usuarios
    private void updateTabla(){
        TablaUsuarios uT = (TablaUsuarios) this.tablaUsuarios.getModel();
        Set<UsuarioDeMercado> u = FachadaDB.getFachada().getUsuariosDeMercado();
        ArrayList<UsuarioDeMercado> uM = new ArrayList<>();
        
        for(UsuarioDeMercado user: u){
            
            //filtramos los que estén esperando confimación de alta o de baja:
            if(user.getEstado() == EstadoUsuario.SOLICITANDO_ALTA || user.getEstado() == EstadoUsuario.SOLICITANDO_BAJA){
                uM.add(user);
            }
        }
        
        uT.setFilas(uM);
    }
    
    private void displayComision(){
        Double comision = this.usr.getComision_actual();
        String comStr = comision.toString();
        this.ComisionActualCajaTexto.setText(comStr);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BajaPagosBoton;
    private javax.swing.JTextField ComisionActualCajaTexto;
    private javax.swing.JLabel ComisionActualTexto;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton NuevaComisionBoton;
    private javax.swing.JMenuItem SaldosMenuItem;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JMenu UsuarioMenu;
    private javax.swing.JButton botonAutorizar;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
